version: '3.8'

services:
  yunshu:
    build: .
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: yunshu123
      MYSQL_DB: weather_db
      DEEPSEEK_API_KEY: "${DEEPSEEK_API_KEY:-sk-b983565e09174938ba5f02779435e60b}"
      DEEPSEEK_BASE_URL: https://api.deepseek.com
      FUXI_MODEL_DIR: /app/FuXi_EC
      ADMIN_SECRET: "123456"
      HF_HUB_OFFLINE: "1"
      TRANSFORMERS_OFFLINE: "1"
      BACKEND_HOST: "192.168.18.4"   # 老师需要改成自己的服务器IP
    volumes:
      - ./FuXi_EC:/app/FuXi_EC                         # 伏羲模型（可选）
      - ./data/chroma:/app/backend/chroma_weather_index
      - /root/.cache/huggingface:/root/.cache/huggingface   # 模型缓存挂载
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yunshu123
      MYSQL_DATABASE: weather_db
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
